---
title: "DATA"
author: "Erynne Jackson"
date: "2024-12-01"
output: github_document
---

```{r}

library(readxl)
library(tidyverse)
library(readr)

```

Cleaning the Books file. 
```{r}

url = "https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/refs/heads/master/books.csv"
books = read_csv(url)

view(books)
```

Cleaning the Ratings file.  
```{r}

url2 = "https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/refs/heads/master/ratings.csv"
ratings = read_csv(url2)

view(ratings)

```

Cleaning the Book Tags file.  
```{r}
url3 = "https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/refs/heads/master/book_tags.csv"
book_tag = read_csv(url3)

view(book_tag)
```


Cleaning the Tags file. 
```{r}

url4 = "https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/refs/heads/master/tags.csv"
tags = read_csv(url4)

```

Cleaning the To Read file. 
```{r}
url5 = "https://raw.githubusercontent.com/zygmuntz/goodbooks-10k/refs/heads/master/to_read.csv"
to_read = read_csv(url5)

view(to_read)

```
Set Up (KB):
```{r}
library(readr)
library(dplyr)
```

Import data (JM):
```{r}
book_data = read_csv("Books.csv")
head(book_data)
```

Remove unnecessary variables (JM): 
```{r}
book_data = book_data %>%
  select(
    book_id,
    goodreads_book_id,  
    isbn,                
    authors,             
    title,               
    average_rating,      
    ratings_count,       
    work_ratings_count,  
    work_text_reviews_count, 
    ratings_1,           
    ratings_2,           
    ratings_3,           
    ratings_4,           
    ratings_5            
  )
```

Check for missing (JM): 
```{r}
missing_summary = book_data %>%
  summarise(across(everything(), ~ sum(is.na(.)), .names = "{.col}"))

print(missing_summary)
```
There are 700 entries missing from the 'missing_isbn' variable. 

Removing missing values (JM): 
```{r}
book_data_complete = book_data %>%
  filter(!is.na(isbn))
```

Creating new csv file for use (JM): 
```{r}
write.csv(book_data_complete, "book_data_complete.csv", row.names = FALSE)
```


Creating merged tag file (SR)
```{r}
merged_tags = 
  left_join(book_tag, tags, by = c("tag_id")) %>%
  group_by(goodreads_book_id) %>%
  arrange(desc(count)) %>%
  filter(!tag_name %in% c("owned", "to-read", "favorites", "owned", "books-i-own", "currently-reading", "library", "owned-books", "to-buy", "kindle", "default", "ebook", "audiobook", "ebooks", "wish-list", "my-library", "audiobooks", "i-own", "book-club", "discworld", "harry-potter", "tolkien", "series",
"all-time-favorites", "1001", "1001-books", "	
1001-books-to-read", "1001-books-to-read-before-you-die", "1001-import", "abandoned", "pulitzer-prize", "dune", "unfinished", "19th-century", "novels", "time-100", "paul-auster", "favourites", "ayn-rand", "anne-tyler", "ux", "dan-brown", "john-grisham", "grisham", "books-about-books", "shakespeare", "read-for-school", "nelson-demille", "paulo-coelho", "jane-austen", "pulitzer", "steve-martini", "	
terry-pratchett", "middle-earth")) %>%
  drop_na(tag_name) %>%
  slice_head(n = 5) %>%
  ungroup()
  

  
#Cleaning up genres

genres <- list(
  "young adult" = c("young-adult", "ya"),
  "children" = c("children", "childrens", "childhood", "children-s", "childrens-books", "children-s-books", "kids", "kids-books", "baby"),
  "fantasy" = c("fantasy", "fantasy-fiction"), 
  "science fiction" = c("sci-fi", "science-fiction", "sci-fi-fantasy", "scifi", "sf", "cyberpunk", "epic-fantasy", "high-fantasy"),
  "dystopian" = c("dystopia", "dystopian"),
  "non-fiction" = c("non-fiction", "nonfiction"),
  "classics" = c("classic", "classics", "clàssics"),
  "mystery" = c("mystery", "mysteries", "detective", "mystery-thriller"),
  "romance" = c("historical-romance", "paranormal-romance", "historical romance", "romance-suspense"),
  "poetry" = c("poetry", "poem"),
  "biography" = c("biography", "biographies"),
  "spirituality" = c("spiritual", "spirtuality"),
  "self-help" = c("self-improvement", "self-help", "personal-development"),
  "art" = c("art", "art-books"),
  "finance" = c("personal-finance", "finance", "money"),
  "business" = c("management", "leadership", "productivity", "entrepreneurship"),
  "graphic novels" = c("graphic-novels", "manga" ),
  "food" = c("food", "cooking", "cookbooks", "cookbook"), 
  "lgbtq" = c("lgbt", "gay", "queer", "glbt"),
  "christianity" = c("christian-living", "christian")
)

# Create a function to standardize tags
standardize_tag <- function(tag) {
  # Check each genre list for a match
  for (genre in names(genres)) {
    if (tag %in% genres[[genre]]) {
      return(genre)
    }
  }
  # If no match, return the original tag
  return(tag)
}

# Apply the function to the tag_name column
rename_tags <- merged_tags %>%
  mutate(tag_name = sapply(tag_name, standardize_tag))



pivoted_data <- rename_tags %>%
  mutate(rank = row_number(), .by = goodreads_book_id) %>% # Add rank for top tags
  pivot_wider(
    id_cols = goodreads_book_id, 
    names_from = rank, 
    values_from = c(tag_name), 
    names_prefix = "top_"
  )


books_with_tags <- left_join(book_data_complete, pivoted_data, by = c("goodreads_book_id"))

write.csv(books_with_tags, "books_with_tags.csv", row.names = FALSE)
```