---
title: "<b>To Be Read or Not To Be Read</b>"
output: html_document     
---

```{r setup, include = FALSE}
library(readr)
books_with_tags <- read_csv("books_with_tags.csv")
```

### **Motivation**
With the New Year right around the corner, countless sources are providing their list of the ‘Best Books’ of the year. These lists help inform readers while providing them with book recommendations that interest them. Our overarching goal is to understand trends of readers using GoodReads. 

GoodReads is an online platform to find, share, and rate books readers have read. This information can help publishers, authors, and libraries tailor their book selections to meet reader's demands and promote lesser-known genres and authors. Understanding this can also help explore cultural trends that resonate with the public, while identifying or creating opportunities for reader re-engagement. 

### **Project Inspiration**
With the demanding workload of graduate school, there’s little time to sit down and enjoy a good book. However, with winter break approaching, we’re all looking forward to some much-needed rest and the chance to indulge in quality reading time! This project was inspired by a shared hobby among our team and our collective anticipation for the opportunity to relax on the couch, sip some coffee, and dive into a good book.

### **Initial Questions**
The initial research question of our project was: What are trends among readers? This initial research question aided us when exploring datasets. Once we found GoodBooks-10K, an open data source hosted on GitHub with data from GoodReads, we were interested in exploring trends among readers using GoodReads. The team spent time understand what data was available and then created the following questions to guide this project: 

- Who are the top fifteen GoodReads users, by Ratings and To-Read? 
- Are sequels worth reading?
- What are the top 10 most and least popular genres?
- Who are the top 10 most and least popular authors? 
- How can we build a recommendations page based on the data provided? 


### **Data** 

The original data for this project is from GoodBooks-10K and is from an open data source hosted on GitHub with data from GoodReads. We used the following datasets from the original GoodBooks-10K data: book_tags.csv, books.csv, ratings.csv, tags.csv, and to_read.csv. 

Our main dataset is called `r books_with_tags`. This dataset was created by merging the books.csv with book_tags.csv. This dataset had a sample size of 9300 books and each book has five top tags. On GoodReads, tags are non-exclusive virtual shelves that users can organize their books on. In the raw data, books had between 1-25 tags, we took the five most common tags for each book and kept those in the books_with_tags.csv dataset. The tags in this dataset are used as proxies for genres. 

The books_with_tags dataset contains the following variables: 

- book_id:  
- goodreads_book_id:
- isbn: International Standard Book Number
- authors: author name (first, last)
- title: title of the book
- average_rating: average goodreads user rating of a book
- ratings_count: the total count of ratings for a book
- work_ratings_count: 
- work_text_reviews_count:
- ratings_1: Total count of users who rated book as 1 star 
- ratings_2: Total count of users who rated book as 2 star 
- ratings_3: Total count of users who rated book as 3 star 
- ratings_4: Total count of users who rated book as 4 star 
- ratings_5: Total count of users who rated book as 5 star 
- image_url: url link to book image 
- top_1: first top tag for the book, used as a proxy for genre 
- top_2: second top tag for the book, used as a proxy for genre 
- top_3: third top tag for the book, used as a proxy for genre 
- top_4: fourth top tag for the book, used as a proxy for genre 
- top_5: fifth top tag for the book, used as a proxy for genre 

### **Exploratory Analysis**

#### **Who are the top fifteen GoodReads users, by Ratings and To-Read?**

To explore this question, we used the following datasets: cleaned books data, books_with_tags.csv, ratings.csv, and to_read.csv. Separate data frames were made to find the top 15 users by ratings and by number of to-read books.

For general analysis, the average rating by each of the top 15 users was summarized. This distribution was visually compared to the average ratings of the entire GoodReads community and found that the Top 15 ratings data was bimodal. 

[insert graph]

The average rating among the Top 15 users was 3.756 while among the community it was 3.929. The three most rated genres for the top 15 users were found–exploratory analysis showed that there were too many tags per book and too many ratings per user to have a clean descriptive analysis, so top three rated genres for each user were found. The visualized data looked at which of each user’s top three genres was most common among the group of fifteen. Among the top 15 by ratings, the most popular genres were fiction and classics, with all 15 of the 15 users having fiction as one of their top three rating genres and 13 of the 15 users having classics. 

For the top 15 users by number of to-read, all of the books each of the selected users were compiled and then analyzed to find the top 15 most popular books among the top 15 users. The first three most popular were “The Catcher in the Rye”, “The Fault in Our Stars” and “A Tale of Two Cities.” The top want-to-read genres were also analyzed among the selected 15. First they were analyzed by looking at which genres were most common and how many users had one of these genres as their top three. Fiction (13/15), young adult (9/15), and fantasy (8/15) were the most common genres among users’ top three genres. Then the next analysis was looking at all data as a whole rather than by user. The top genre tag for all distinct book titles were compiled to visualize in a bar graph the most popular genres the top 15 users wanted to read overall. The most popular genre was young adult, with 177 distinct titles to be read, while others included classics (151) and fiction (124).

#### **Are sequels worth reading?**

To investigate whether sequels are worth the read, we start by assessing the distribution of series lengths with a bar plot. We utilized data from the books_with_tags.csv dataset and conducted a string extraction to identify information on the order of books within a series and series name, creating the variables “series_number” and “series_name”. We also created a series length variable by finding the maximum of the series_number variable. These variables were created in a new dataset called sequels. We plotted the distribution of series length on a barplot and found that the majority of series are one book, with the next largest groups being sequels and trilogies. 

[insert graph here]

We then filtered the sequels dataset to look at the average ratings of the first two books of each series. To explore whether sequels are rated higher than their original books, we used a box plot to visualize the comparison between the average ratings of the first and second books in a series. This box plot showed that the median rating for sequels is slightly higher than that of the first book. 

[insert graph here]

Next, to formally test whether sequels are rated higher than their original works using statistical methods, we conducted an independent two sample t-test comparing the average ratings of the first and second books. We assessed normality using the box plots and found that the distribution of average ratings appeared to be normal in both the first and second books. The null and alternative hypotheses for the test are as follows:

- Null hypothesis: The mean average rating of first books is equal to the mean average rating of second books.
- Alternative hypothesis: The mean average rating of first books is not equal to the mean average rating of second books.

[insert t test table]

The t-test results showed a p-value < 0.05, indicating a statistically significant difference between the two book groups. On average, the sequel is rated 0.094 stars higher than the first books (95% CI: 0.023, 0.165). These results support the hypothesis that on average, sequels are better well-received than their original works by good reads users. 

Based on the analyses, most series tend to be shorter in length, with single books, sequels, and trilogies being the most common. Additionally, sequels tend to be rated higher than the first book, as supported by visual representations and statistical testing. These results suggest that readers may enjoy a continued storyline or character development. The prevalence of shorter series lengths may reflect reader preference or publishing company strategies to maximize reader engagement. 

#### **What are the top 10 most and least popular genres, among read books?**

For the most and least popular genre analysis, we used the books_with_tags.csv dataset (n=9300). We used the pivot_longer function from the tidyr package to create a single column for tags, called “  “ (n=XXX). This allowed me to analyze the most and least popular genres based on tags. 

After some descriptive analysis, we found that the most popular tag is “fiction” and the third most popular tag is “non-fiction.” However, some would argue that in modern literature these tags are considered the broadest category of genre but do not provide information about the specific fiction or nonfiction genres readers are reading or interested in reading. Therefore, the decision to exclude these two categories was made. There are 1,348 distinct genre categories, based on tags.  

We grouped the data by tag value and then calculated the number of occurrences for each tag. We then sorted the tags by count in descending order and selected the top 10 most popular tags. A bar plot was created to display the top 10 genres based on tags. The 10 most popular genres read, in order, are: Young Adult, Fantasy, Romance, Science Fiction, Children, Mystery, Classics, Historical Fiction, Contemporary, and Thriller. 

(GRAPH)
A similar process as above was used to identify the 10 least popular genres. We found there was a substantial number of tags that were only used once, twice, or three times but this information was not useful when presented on a bar graph. Therefore, we decided to exclude all tags that have a tag count of less than 100. A cut off tag count of 100 was used because we wanted to focus on tags that have a moderate level of user engagement. By using a threshold of 100 for tag count, the analysis ensures that the least popular genres identified still have sufficient user recognition and can represent meaningful patterns in the data.  The 10 least popular genres read, in order, are: Manga, Adult Fiction, Religion, Art, War, Memoirs, IGBTQ, Poetry, Drama, and Middle Grade.

(GRAPH)

#### **What are the top 10 most and least popular genres, among to-be-read books?**

For the most and least popular to-be-read genre analysis, we merged the to_read.csv and books_with_tags.csv datasets on book_id using an inner join, to create to_read_with_tags.csv. We created a single column/variable for tags and removed fiction and non-fiction tags, as done in the previous analysis. 

The same process was followed, as described above, to identify the 10 most popular and 10 least popular genres, among to-be-read books. The 10 most popular genres to-be-read, in order, are: Young Adult, Fantasy, Romance, Science Fiction, Children, Mystery, Classics, Historical Fiction, Contemporary, and Thriller. The 10 least popular genres read, in order, are: Manga, Adult Fiction, Religion, Art, War, Memoirs, IGBTQ, Poetry, Drama, and Middle Grade. 

(GRAPHS)

The rankings were the same for books read and book to-be-read, this was expected since we expect the genres that users are reading to be similar to genres that users are planning to-read.This consistency highlights a strong alignment between what users are reading and what they plan to read, reinforcing the persistence of genre preferences across user behavior.

#### **What are the most and least popular authors?**

To observe genre popularity, we started by calculating the total number of ratings for each author from the book data.csv. We grouped authors and summarized by the total ratings using the sum() function to determine the authors with the highest cumulative ratings. We sorted the data in ascending order to determine the least-read authors and descending order for the most-read authors based on their total ratings. We then extracted the top 10 entries from each sorted dataset to represent the most-read and least-read authors, respectively, For popular authors, we calculated the percentage of total ratings contributed by each author to assess their relative popularity within the dataset. In order to do this, each of the author's total ratings were divided by hr overall sum of ratings and then multiplied (the times) by 100. We then sorted the data in descending order based on the percentages to display the top 10 popular authors.  

The visualization of the least-read, most-read, and popular authors were essential in displaying the descriptive analyses. We created bar charts and tables using ggplot and knitr to display the data in an accessible format. Bar charts and tables complemented each other by providing both visual comparisons and detailed numerical information to highlight trends in engagement across authors.  For the least-read, most-read and popular authors, we created bar charts to display the total ratings of the authors with the highest, lowest and most engagement. The least-read authors were sorted in ascending order, displaying minimal engagement, while the most-read authors were sorted in descending order to showcase those with the highest engagement. For popular authors, we created a percentage-based bar chart to display the relative contribution of each author’s ratings to the overall dataset. 

[insert graph]

Our analysis displaying the most-read authors included J.K. Rowling and Suzanne Collins. These findings aligned with our expectations, as these authors have written popular books such as the Harry Potter and The Hunger Games series. In contrast, the least-read authors were those with minimal engagement, often having only one book in the dataset. The exploration of popular authors based on their percentage of total ratings highlighted the relative impact of these authors in the overall dataset. Authors like J.K. Rowling not only dominated in overall total ratings but also in their percentage contributions, reflecting their popularity compared to others. Our findings further underscored the visibility of published works and its impact on the author's readership. Authors with more books in the dataset tended to have higher total ratings, suggesting a cumulative effect of engagement. However, our percentage analysis revealed that some authors achieve high relative engagement even with fewer books, pointing to the quality of their work.  

#### **How can we build a recommendations page based on the data provided?**

Using the Shiny App, we created a data-based book recommendations page. Users can receive recommendations based on their favorite author, genre, and preferred book rating. Once users fill out their information, the app lists up to five books based on the user’s search criteria. Below is a screenshot of the book recommendation page. 

(Insert picture here once website is completely set up)

Starting with the books_with_tags.csv dataset, we restricted the dataset to the variables of interest and rounded the ‘average_rating’ variable to the nearest half number. After creating the final dataset, we built the User Interface. We added conditions that allow users to select a genre or author to base their recommendations on. Because some books were classified under multiple genres, users can choose more than one genre to narrow their recommendations. We also allow users to limit to a specific book rating, no matter which search criteria they use. If no books match the criteria, we alter the interface so that they will receive book recommendations that still match their genre and author preference, but will have a lower rating than they specified. We indicate that the book listed is not based on their rating preference next to the book title. We restricted the resulting list to five books. 

### **Discussion & Limitations**

The overarching goal of this project was to understand trends of readers using Goodreads. We found the average rating among the Top 15 users was 3.756. Among those Top 15 readers, the most popular genres were fiction and classics with the most popular books read being “The Catcher in the Rye”, “The Fault in Our Stars” and “A Tale of Two Cities.” 

We investigated if sequels were worth reading, and found that most series tend to be shorter in length, with single books, sequels, and trilogies being the most common. Additionally, sequels tend to be rated higher than the first book, suggesting that readers may enjoy a continued storyline or character development. 

We found that among read and to-be-read books, the 10 most popular genres are Young Adult, Fantasy, Romance, Science Fiction, Children, Mystery, Classics, Historical Fiction, Contemporary, and Thriller. The 10 least popular genres are Manga, Adult Fiction, Religion, Art, War, Memoirs, IGBTQ, Poetry, Drama, and Middle Grade. Additionally, the most-read authors included J.K. Rowling and Suzanne Collins. 

To help users find recommendations through our website, we created a Recommendations page using the Shiny App. With these features users will be recommended up to five books based on rating and author preferences. 

A limitation for our project is the lack of temporal information in the Goodreads dataset we selected for our analyses; the dataset did not include variables that specified when the data was collected or when ratings were published. This absence of time-related variables limited our ability to determine trends in genre, author, and book popularity. Additionally, as we do not have information on when the dataset was compiled, we cannot determine how relevant the ratings metrics are for current reading trends. 


