---
title: "<b>Least Read Authors</b>"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(dplyr)
library(tidyr)
library(lubridate)
library(janitor)
library(ggplot2)
```

## Data Import
```{r books, echo=FALSE}
#Read CSV file 
books <- read.csv("books.csv")
```

```{r most read authors, echo=FALSE}
least_read_authors <- books %>%
  group_by(authors) %>%
  summarize(
    total_ratings = sum(work_ratings_count, na.rm = TRUE), 
    num_books = n() 
  ) %>%
  arrange(total_ratings) 

```

### *Displaying  Top 10 Least Read Authors*

```{r Dislaying Top 10 Least Read Authors, echo=FALSE}
ggplot(head(least_read_authors, 10), aes(x = total_ratings, y = reorder(authors, total_ratings))) +
  geom_bar(stat = "identity", aes(fill = total_ratings), show.legend = FALSE) +
  labs(
    title = "Top 10 Least Read Authors by Ratings",
    x = "Total Ratings Count",
    y = "Authors"
  ) +
  scale_fill_gradient(low = "red", high = "darkred") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),  
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"), 
    panel.grid.major.y = element_blank() 
  ) +
  scale_x_continuous(labels = scales::comma)
```

**Top 10 Least Read Authors**


This bar chart, "Top 10 Least Read Authors by Ratings" depicts the percentage of total ratings each author received relative to the dataset.

```{r, echo=FALSE}
# Load required library
library(knitr)

# Display the least read authors as a table
least_read_authors %>%
  head(10) %>%  # Select the first 10 least read authors
  kable(caption = "Table: Top 10 Least Read Authors by Total Ratings")

```


