---
title: "<b>Most Read Authors</b>"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(dplyr)
library(tidyr)
library(lubridate)
library(janitor)
library(ggplot2)
library(knitr)
```

## Data Import
```{r books, echo=FALSE}
#Read CSV file 
books <- read.csv("books.csv")
```

### *Summarizing Read Counts by Author*
```{r most read authors, echo=FALSE}
most_read_authors <- books %>%
  group_by(authors) %>%
  summarize(
    total_ratings = sum(work_ratings_count, na.rm = TRUE), 
    num_books = n() #Counting the number of books per author
  ) %>%
  arrange(desc(total_ratings))

head(most_read_authors, 50)
```


### *Displaying  Top 10 Most Read Authors*
```{r Dislaying Top 10 Most Read Authors, echo=FALSE}
most_read_authors = ggplot(head(most_read_authors, 10), aes(x = total_ratings, y = reorder(authors, total_ratings))) +
  geom_bar(stat = "identity", aes(fill = total_ratings), show.legend = FALSE) +
  labs(
    title = "Top 10 Most Read Authors by Ratings",
    x = "Total Ratings Count",
    y = "Authors"
  ) +
  scale_fill_gradient(low = "red", high = "darkred") + 
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5), 
    axis.text.y = element_text(size = 10), 
    axis.text.x = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"), 
    panel.grid.major.y = element_blank() 
  ) +
  scale_x_continuous(labels = scales::comma)

print(most_read_authors)

ggsave("report visualizations/most_read_authors.png", plot = most_read_authors, width = 10, height = 6)
```

**Top 10 Most Read Authors**

This bar chart, "Top 10 Most Read Authors by Ratings" depicts the percentage of total ratings each author received relative to the dataset.

```{r echo=FALSE}
most_read_authors <- data.frame(
  Author = c("J.K. Rowling, Mary GrandPré", "Suzanne Collins", "Stephenie Meyer",
             "Stephen King", "Rick Riordan", "J.R.R. Tolkien", "Dan Brown",
             "Cassandra Clare", "Nicholas Sparks", "John Green"),
  Total_Ratings = c(14126791, 9161124, 8631937, 7297834, 5717999, 
                    5602790, 5332589, 4631019, 4501871, 4312589),
  Number_of_Books = c(8, 9, 11, 60, 22, 6, 7, 13, 19, 4)
)

# Create a static table with knitr::kable
most_read_authors |>
  kable(caption = "Top 10 Most Read Authors by Total Ratings")
```

