--- 
title: "P8105 Final Project"
output: github_document
Name: Jasmin Martinez (jrm2319), Samiha Reza (sr4081), Kamiah Brown (kab2310), Erynne Jackson (ej2520), Elliot Kim (ek3376)
Date: 11/04/24
---
Authors: Jasmin Martinez (jrm2319), Samiha Reza (sr4081), Kamiah Brown (kab2310), Erynne Jackson (ej2520), Elliot Kim (ek3376)

**The motivation for this project**: 
For this project, we would like to better understand reader’s genre and author preferences in the United States. By identifying which genres and authors are most and less read, as well as frequently kept/unkept, we can gain insights into trends of literary engagement. This information could provide publishers, authors, and libraries insight into tailoring their offerings to meet reader’s demand and promoting less-read genres. Understanding popular genres and authors can also help explore cultural trends that resonate with the general public while identifying lesser-read genres to create opportunities for re-engagement. 

**The intended final products**:
Website with: 
About
Analysis 
Dashboard
Report – Hypothesis Testing Results
Recommendations page


**The anticipated data sources**: 
We plan to use open source data from GoodReads: (https://github.com/zygmuntz/goodbooks-10k)


**The planned analyses/visualizations/ coding challenges**: 
Planned analyses include finding the most read/least read/most to-be-read genres, and statistics on the top ten users. Planned visualization on types of books, timelines for reading and adding books, book ratings, and top ten users. We will use analyses and visualizations to create a data-based recommendation list.


**Planned Timeline**: 

Nov. 4: Initial Planning Meeting


Nov. 8, 1:00pm: Submit Proposal


Nov 11-18: Project Review Meeting


(Tentative) Nov 18: Group Check-In #1


(Tentative) Nov 25: Group Check-In #2


(Tentative) Dec 2: Group Check-In #3: Project Draft Due (Internal)


Dec 2-7: Edit and Finalize Project 


Dec 7, 11:59pm: Submit Report


Dec 7, 11:59pm: Webpage and screencast due  


Dec 7, 11:59pm: Peer Assessment due


Dec 12:In-Class Discussion of Projects 



