---
title: "Popular Authors"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(dplyr)
library(tidyr)
library(lubridate)
library(janitor)
library(ggplot2)
```

## Data Import
```{r books, echo=FALSE}
#Read CSV file 
books <- read.csv("books.csv")
```

### Summarizing Read Counts by Author 
```{r most read authors}
most_read_authors <- books %>%
  group_by(authors) %>%
  summarize(
    total_ratings = sum(work_ratings_count, na.rm = TRUE) # Summing up ratings for each author
  ) %>%
  arrange(desc(total_ratings)) %>%
  mutate(
    percentage = (total_ratings / sum(total_ratings)) * 100 # Calculate percentage of total ratings
  ) %>%
  head(10) #
```
### Displaying  Popular Authors
```{r Dislaying Popular Authors}
ggplot(most_read_authors, aes(x = reorder(authors, -percentage), y = percentage)) +
  geom_bar(stat = "identity", fill = "darkred") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), vjust = -0.5, size = 4) + # Add percentage labels
  labs(
    title = "Top 10 Popular Authors by Percentage",
    x = "Authors",
    y = "Percentage of Total Ratings"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5), # Center and bold title
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10), # Rotate x-axis labels
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12, face = "bold")
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) # Format Y-axis as percentage
```

The top 10 most read 