---
title: "Sequels"
author: "ek3376"
date: "2024-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(knitr)
library(broom)

```

### Load and clean the datasets
```{r}
sequel = read.csv("book_data_complete.csv")

sequel_data <- sequel |>
  mutate(series = str_extract(title, "\\(.*\\)"), 
         series_number = as.numeric(str_sub(str_extract(series, ', #[0-9]+\\)$'),4,-2)),
         series_name = str_sub(str_extract(series, '\\(.*,'),2,-2)) |>
  filter(series_number %in% c(1, 2))
```

### Visualization of Average Ratings of First Book vs Sequel
```{r}
ggplot(sequel_data, aes(x = factor(series_number), y = average_rating, color = factor(series_number))) +
  geom_boxplot() +
  coord_cartesian(ylim = c(3, 5)) +
  labs(x = "Book in Series", y = "Average Rating") +
  scale_color_manual(values = c('blue', 'red')) +
  theme_minimal() +
  theme(legend.position = "none") 
```

### Chi-Square Test
```{r}
t_test_result <- t.test(average_rating ~ series_number, data = sequel_data)

t_test_table <- t_test_result |>
  tidy() |>
  knitr::kable(caption = "T-Test Results: Comparing Ratings of First and Second Books")

print(t_test_table)
```

### Regression
```{r}
lm_sequel <- lm(average_rating ~ factor(series_number) + factor(series_name), data = sequel_data)

summary(lm_sequel)
```