---
title: "Top Users by To Read"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(plotly)
library(readr)
library(knitr)
library(tidyverse)
ratings <- read_csv("./ratings.csv")
to_read <- read_csv("./to_read.csv")
books_with_tags <- read_csv("./books_with_tags.csv")
```

```{r}
#Count how many to-reads each user has
to_read_counts <- to_read %>%
  group_by(user_id) %>%
  summarize(total_to_read = n(), .groups = 'drop') %>%
  arrange(desc(total_to_read))

#Select the top 15 users with the most to-reads
top_user_ids_to_read <- to_read_counts %>%
  head(15)

#Create dataframe with all the books the top 15 users said they wanted to read. Count how many times these books were selected by users. Select the top 15 to-read books by the top 15 users
top_to_read <- semi_join(to_read, top_user_ids_to_read, by = c("user_id"))

top_to_read_count <- top_to_read %>%
  count(book_id) %>%
  arrange(desc(n)) %>%
  head(15) 

#Add book information to the 15 books
top_ratings_titles <- left_join(top_to_read_count, books_with_tags, by = c("book_id")) %>%
  select(title, authors, n) %>%
  rename("Number of Top Users" = n) %>%
  rename("Title" = title) %>%
  rename("Authors" = authors)


kable(top_ratings_titles, caption = "Top 15 To-Read books for Top 15 Users", align = "c")

```

```{r}
top_to_read_genres <- left_join(top_to_read, books_with_tags, by = c("book_id")) %>%
  group_by(user_id) %>% 
  pivot_longer(cols = starts_with("top"),
               names_to = "tag_type",
              values_to = "tag") %>%
  group_by(user_id, tag) %>%
  summarise(tag_count = n(), .groups = "drop") %>%
  drop_na(tag) %>%
  group_by(user_id) %>%
  slice_max(order_by = tag_count, n = 3) %>%
  ungroup()

unique_data <- !duplicated(top_to_read$book_id)

```