---
title: "Top Users By Ratings"
author: "Samiha Reza"
date: "2024-12-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(plotly)
library(readr)
library(knitr)
library(tidyverse)
library(ggplot2)
ratings <- read_csv("./ratings.csv")
to_read <- read_csv("./to_read.csv")
books_with_tags <- read_csv("./books_with_tags.csv")
```

```{r data_1}
# Count the number of ratings per user
users_ratings <- ratings %>%
  group_by(user_id) %>%
  summarize(total_ratings = n(), .groups = 'drop') %>%
  arrange(desc(total_ratings))

```

```{r ratings_users, echo = FALSE}
# Select the top 15 users by number of ratings
top_user_ids_rat <- users_ratings %>%
  head(15)

# Compile all ratings done by the top 15 users
top_ratings <- semi_join(ratings, top_user_ids_rat, by = c("user_id"))

# Find the average rating of each user
avg_rat <-top_ratings %>%
  group_by(user_id) %>%  
  summarize(avg_rating = mean(rating, na.rm = TRUE))

# Include number of ratings per user with the average rating
top_users <- left_join(top_user_ids_rat, avg_rat, by = c("user_id")) %>%
  rename("User ID" = user_id) %>%
  rename("Total Ratings" = total_ratings) %>%
  rename("Average Rating" = avg_rating)

  
# Print table of average ratings
kable(top_users, caption = "Average Ratings and Number of Ratings for Top 15 Raters", align = "c")



over_avg_rat <-ratings %>%
  group_by(user_id) %>%  
  summarize(avg_rating = mean(rating, na.rm = TRUE))


# Overlay density plots
ggplot() +
  geom_density(data = top_users, aes(x = `Average Rating`), fill = "blue", alpha = 0.5) +
  geom_density(data = over_avg_rat, aes(x = avg_rating), fill = "red", alpha = 0.5) +
  labs(title = "Average Ratings Distribution for All Raters vs Top 15 Raters",
       x = "Rating", y = "Density") +
  theme_minimal() +
  theme(legend.title = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    legend.background = element_rect(fill = "gray90"),
    legend.position = "top")


# Creates a data frame that includes the book information for each of the ratings in top_ratings. Then found the three most rated genres for the top 15 users. 
top_ratings_genres <- left_join(top_ratings, books_with_tags, by = c("book_id")) %>%
  group_by(user_id) %>% 
  pivot_longer(cols = starts_with("top"),
               names_to = "tag_type",
              values_to = "tag") %>%
  group_by(user_id, tag) %>%
  summarise(tag_count = n(), .groups = "drop") %>%
  drop_na(tag) %>%
  group_by(user_id) %>%
  slice_max(order_by = tag_count, n = 3) %>%
  ungroup()


# Counted how many of the 15 users rated a genre out of the groups top three's
genres_count <- top_ratings_genres %>%
  count(tag)

```

```{r plot}
# create a pie chart to show all genres
genres_count %>%
  plot_ly(labels = ~tag, values = ~n, type = "pie", colors = "viridis")
  
```
  