---
title: "Popular Authors"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(dplyr)
library(tidyr)
library(lubridate)
library(janitor)
library(ggplot2)
library(knitr)
```

## Data Import
```{r books, echo=FALSE}
#Read CSV file 
books <- read.csv("books.csv")
```

```{r most read authors, echo=FALSE}
most_read_authors <- books %>%
  group_by(authors) %>%
  summarize(
    total_ratings = sum(work_ratings_count, na.rm = TRUE) # Summing up ratings for each author
  ) %>%
  arrange(desc(total_ratings)) %>%
  mutate(
    percentage = (total_ratings / sum(total_ratings)) * 100 # Calculate percentage of total ratings
  ) %>%
  head(10) #
```

### *Displaying  Popular Authors*
```{r Dislaying Popular Authors, echo=FALSE}
ggplot(most_read_authors, aes(x = reorder(authors, -percentage), y = percentage)) +
  geom_bar(stat = "identity", fill = "darkred") +
  geom_text(aes(label = sprintf("%.1f%%", percentage)), vjust = -0.5, size = 4) + 
  labs(
    title = "Top 10 Popular Authors by Percentage",
    x = "Authors",
    y = "Percentage of Total Ratings"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5), 
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
    axis.text.y = element_text(size = 10),
    axis.title = element_text(size = 12, face = "bold")
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) 
```


This bar chart, "Top 10 Popular Authors by Percentage of Total Ratingss" depicts the percentage of total ratings each popular author received relative to the dataset.

```{r, echo=FALSE}
top_10_authors <- books %>%
  group_by(authors) %>%
  summarize(
    total_ratings = sum(work_ratings_count, na.rm = TRUE)
  ) %>%
  arrange(desc(total_ratings)) %>%
  mutate(
    percentage = (total_ratings / sum(total_ratings)) * 100
  ) %>%
  head(10) # Select the top 10 authors

# Create a table
top_10_authors %>%
  kable(
    caption = "Top 10 Popular Authors by Percentage of Total Ratings",
    col.names = c("Author", "Total Ratings", "Percentage of Total Ratings")
  )
```

